Update Moderator Dashboard
calblueprint/nbjc pull request #13
Opened 2020-10-19 02:11 UTC by Sonjajo

Updated Moderator Dash with clickable apps on the left that expand to the right; added some new sample-data. 
Used the material-UI card component for the left and right cards. CSS for cardDetail on the right can still use some work, will fix this on this week's sprint when I make the form.

## Related PRs

_Optional - any related PRs you're waiting on, or PRs that will conflict, etc_

## Migrations

_Optional - if you added anything to the database through migration(s)_

## Screenshots

_Required for visual changes_
![image](https://user-images.githubusercontent.com/30053749/96393917-7cf1cf80-1175-11eb-91a0-ece32c6521c1.png)

CC: @kwfk

2020-10-20 19:22 UTC, kwfk requested changes
nice work!

2020-10-20 19:22 UTC, kwfk commented on pages/moderator/index.tsx
> +const ModList: React.FunctionComponent<Props> = ({ items }) => {
Let's name this ModeratorDashboard

2020-10-20 19:22 UTC, kwfk commented on pages/moderator/index.tsx
> +            {' '}
delete spaces

2020-10-20 19:22 UTC, kwfk commented on pages/moderator/index.tsx
> +            </button>
let's use filled MaterialUI buttons with primary color for accept and secondary for decline

2020-10-20 19:22 UTC, kwfk commented on components/OrgCard.tsx
> +    <Card className={styles.root}>
Add `CardActionArea` to make the card seem clickable
https://material-ui.com/components/cards/#media

2020-10-20 19:22 UTC, kwfk commented on pages/moderator/index.tsx
> +          {items.map((a) => (
replace `a` with something more descriptive

2020-10-20 19:22 UTC, kwfk commented on components/OrgCard.tsx
> +    <Card className={styles.root}>
You may need to fix the styling because it move the image to the top for some reason

2020-10-20 20:51 UTC, Sonjajo commented on components/OrgCard.tsx
> +    <Card className={styles.root}>
done, and fixed!

2020-10-21 02:04 UTC, kwfk approved these changes
I made some refactoring changes so take a look at those but otherwise LGTM

2020-10-21 23:36 UTC, kwfk commented
actually @calblueprint/nbjc everyone should read this

2020-10-21 23:40 UTC, merged