Bryanna/visual admin dashboard
calblueprint/nbjc pull request #15
Opened 2020-10-22 00:14 UTC by bry-gavino

_Describe your feature here_

Made Admin Dash pages (I also accidentally made the Admin Mod page) along with functional links to help navigate. I'll guide through these links in the screenshots section.

I also made an AdminTable component. It's not functioning the way I want it to yet (still trying to figure out how to make it dynamic). The buttons I made for the table seem to break abstraction barriers to me, but I wanted to run it through you first.

## Screenshots

These are links which go to each page (separated by commas):
<img width="368" alt="Screen Shot 2020-10-21 at 5 08 16 PM" src="https://user-images.githubusercontent.com/60284767/96803029-0694dd80-13c0-11eb-8229-303fe4a93e08.png">

Accidentally made the Admin Mod :'DD (all good tho cuz it was fun):
<img width="1398" alt="Screen Shot 2020-10-21 at 5 09 03 PM" src="https://user-images.githubusercontent.com/60284767/96803080-23311580-13c0-11eb-8790-cdf892d5c2c1.png">

We can go back to the homepage by clicking on "NBJC" in the upper left corner:
<img width="177" alt="Screen Shot 2020-10-21 at 5 09 48 PM" src="https://user-images.githubusercontent.com/60284767/96803144-478cf200-13c0-11eb-9d1d-4c6c077a7289.png">

Admin Index page:
<img width="1397" alt="Screen Shot 2020-10-21 at 5 10 47 PM" src="https://user-images.githubusercontent.com/60284767/96803176-612e3980-13c0-11eb-80a2-9b7787939703.png">

We can click on these individual buttons to navigate to the other pages (except Questions--no page created for Questions yet):
<img width="231" alt="Screen Shot 2020-10-21 at 5 11 05 PM" src="https://user-images.githubusercontent.com/60284767/96803206-7acf8100-13c0-11eb-8aef-269987608170.png">

Organizations page:
<img width="1393" alt="Screen Shot 2020-10-21 at 5 11 51 PM" src="https://user-images.githubusercontent.com/60284767/96803220-8c188d80-13c0-11eb-972c-ca5f59a13883.png">

Users page (I didn't see a design for it on Figma so I left it black, but I made it fairly easy to implement any component--like AdminTable--into the page):
<img width="1398" alt="Screen Shot 2020-10-21 at 5 13 09 PM" src="https://user-images.githubusercontent.com/60284767/96803268-b66a4b00-13c0-11eb-8aa6-f6e4095da326.png">

CC: @kwfk

2020-10-28 12:52 UTC, bry-gavino commented
<img width="1397" alt="Screen Shot 2020-10-28 at 5 49 04 AM" src="https://user-images.githubusercontent.com/60284767/97438237-c498f980-18e1-11eb-92ab-49106d352180.png">
<img width="1398" alt="Screen Shot 2020-10-28 at 5 48 46 AM" src="https://user-images.githubusercontent.com/60284767/97438239-c5319000-18e1-11eb-8d7a-8871f1c8cee8.png">
<img width="1390" alt="Screen Shot 2020-10-28 at 5 48 37 AM" src="https://user-images.githubusercontent.com/60284767/97438241-c5ca2680-18e1-11eb-9d78-ccfb9c841ab2.png">

2020-10-31 02:37 UTC, kwfk requested changes
there are some common changes that should be easy fixes, but there are some other bigger changes that I think will be faster to talk to you
but it's looking great!

2020-10-31 02:37 UTC, kwfk commented on pages/adminDash/Organizations.tsx
> +import { sampleOrgData } from 'utils/sample-data.ts';
no `.ts` in import path
so you also won't need the eslint-disable

2020-10-31 02:37 UTC, kwfk commented on pages/adminDash/Applications.tsx
> +import { sampleOrgAppData } from '../../utils/sample-data.ts';
no `.ts` in import path

2020-10-31 02:37 UTC, kwfk commented on components/adminDash/AdminIndex.tsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
don't need this eslint-disable anymore

2020-10-31 02:37 UTC, kwfk commented on components/adminDash/AdminDrawer.tsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
don't need eslint-disable

2020-10-31 02:37 UTC, kwfk commented on components/adminDash/AdminDash.tsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
don't need eslint-disable

2020-10-31 02:37 UTC, kwfk commented on components/adminDash/AdminTable.tsx
> +/* eslint-disable import/no-extraneous-dependencies */
no need for eslint-disable

2020-10-31 02:37 UTC, kwfk commented on pages/adminDash/Dashboard.tsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
no need for eslint-disable

2020-10-31 02:37 UTC, kwfk commented on pages/adminDash/Users.tsx
> +import { sampleUserData } from 'utils/sample-data.ts';
no `.ts` in import path

2020-10-31 02:37 UTC, kwfk commented on components/adminDash/AdminDrawer.tsx
> +                    color={page === 'Application' ? 'primary' : ''}
use `undefined` instead of ''

2020-10-31 02:38 UTC, kwfk commented on components/adminDash/AdminDrawer.tsx
> +                    color={page === 'Application' ? 'primary' : ''}
and in all other similar places

2020-11-01 02:00 UTC, kwfk requested changes
it looks like the table doesn't differentiate between what page it's in? You can assume that the data you get is what you want to display on the table, but have it so that the column names are based on the keys of the data.
For example, if you given the data:
```JSON
{
    id: 1
    name: 'Fred Kim',
    work: 'coder',
    type: 'test',
    date: 'Oct. 31, 2020'
}
```
It will have the column names: id, name, work, type, date, but if the keys are different, the column names will change accordingly.
Let me know if you have questions about this, and I'll elaborate more.

make sure to remove the old components under AdminDash
also, remove any unused imports

2020-11-01 02:00 UTC, kwfk commented on components/admin/AdminDrawer.tsx
> +// try looking at Next.js documents to see if color can change depend on URL color
remove commetn

2020-11-01 02:00 UTC, kwfk commented on components/admin/AdminIndex.tsx
> +    </header>
don't actually need this because `Layout` is the navbar

2020-11-01 02:00 UTC, kwfk commented on components/admin/AdminDrawer.tsx
> +    </main>
instead of creating an empty space, we want to use flexbox in the parent to push the other content

2020-11-01 02:00 UTC, kwfk commented on components/admin/AdminDrawer.tsx
> +  table: typeof AdminTable;
remove `table` because not being passed in

2020-11-01 02:00 UTC, kwfk commented on components/admin/AdminDrawer.tsx
> +const AdminDrawer: React.FunctionComponent<Props> = ({ table, page }) => (
remove `table`

2020-11-01 02:00 UTC, kwfk commented on components/admin/AdminIndex.tsx
> +                    <IconButton color="primary">
no button

2020-11-01 02:00 UTC, kwfk commented on components/admin/AdminTable.tsx
> +});
use css modules instead

2020-11-01 02:00 UTC, kwfk commented on pages/admin/dashboard.tsx
> +import { useState } from 'react';
we can actually delete this file because we will use the same route as the moderator review

2020-11-01 02:00 UTC, kwfk commented on styles/admin/AdminIndex.module.css
> +  width: 80%;
this should be 100%

2020-11-01 02:00 UTC, kwfk commented on components/admin/AdminTable.tsx
> +          </TableBody>
use
```tsx
<caption>No {head} in database</caption>
```
where head is a new prop that can be 'organizations', 'users', or 'organization applications'

2020-11-03 18:24 UTC, kwfk requested changes
just some cleaning up left!
I committed some changes to the drawer and refactored the components so they match the folder structure (page-specific components should go inside a folder with its stylesheet)

I'll add additional comments about the type errors on AdminTable

2020-11-03 18:24 UTC, kwfk commented on components/admin/AdminDrawer/index.tsx
> +import { Button, Hidden, List } from '@material-ui/core';
keep clean imports by using named exports like this for material ui

2020-11-03 18:24 UTC, kwfk commented on components/admin/AdminIndex/AdminIndex.module.css
> +.layout {
remove unused styles

2020-11-03 18:24 UTC, kwfk commented on components/admin/AdminTable/AdminTable.module.css
> +.table {
remove unused styles

2020-11-03 18:24 UTC, kwfk commented on components/admin/AdminTable/index.tsx
> +      : resetButton;
instead of disabling eslint use if statements instead

2020-11-03 18:24 UTC, kwfk commented on styles/admin/AdminDash.module.css
> +.layout {
delete if unused

2020-11-03 18:24 UTC, kwfk commented on styles/admin/AppIndex.module.css
> +.page {
delete if unused

2020-11-03 18:24 UTC, kwfk commented on styles/admin/AppReview.module.css
> +.content {
delete if unused

2020-11-03 23:25 UTC, kwfk commented on components/admin/AdminTable/index.tsx
> +  data: Array<unknown>;
use `OrgApp | Organization | User` imported from `interfaces`

2020-11-04 01:49 UTC, kwfk requested changes
last change :D

2020-11-04 01:49 UTC, kwfk commented on components/admin/AdminTable/index.tsx
> +}
move this inside the component body and use the return type `React.ReactElement`
you can also use arrow functions like
```typescript
const button = () => {...}
```
inside the function, you also don't have pass in an param bc you have access to pageType

2020-11-04 01:54 UTC, kwfk commented on components/admin/AdminTable/index.tsx
> +  data: Array<OrgApp | Organization | User>;
remember to import from interfaces

2020-11-04 02:59 UTC, kwfk approved these changes
looks good! nice work with all the revisions XD

2020-11-04 03:40 UTC, merged