Bryanna/user profile page
calblueprint/nbjc pull request #21
Opened 2020-11-05 07:19 UTC by bry-gavino

Pages for Users to look at and edit their password and email.
(I added a "Users" link at the top of Layout just so it's easy to access it for now!)

## Screenshots

<img width="1680" alt="Screen Shot 2020-11-04 at 11 17 29 PM" src="https://user-images.githubusercontent.com/60284767/98209640-1fd77700-1ef4-11eb-9386-a116901c7fb9.png">
<img width="1675" alt="Screen Shot 2020-11-04 at 11 17 36 PM" src="https://user-images.githubusercontent.com/60284767/98209644-20700d80-1ef4-11eb-993a-f89d540a452b.png">

_Required for visual changes_

CC: @kwfk

2020-11-09 00:41 UTC, kwfk requested changes
nice work! looks good but there are areas we can clean up
might need to talk to elizabeth about the editing flow
let's also add a cancel button

nice use of components :)

2020-11-09 00:41 UTC, kwfk commented on .env.example
> +PG_PORT=5432
this should match main

2020-11-09 00:41 UTC, kwfk commented on pages/users/sample.tsx
> +export default SampleUser;
put this in `utils/sample_data.ts`

2020-11-09 00:41 UTC, kwfk commented on pages/users/settings_edit.tsx
> +const UserProfSettings: FunctionComponent<{ initial?: number }> = () => {
use React.FunctionComponent or React.FC

2020-11-09 00:41 UTC, kwfk commented on styles/users/SettingsEdit.module.css
> +.content {
separate out the stylesheet between components and the page
(take a look at the other components to see how they're structured)

2020-11-09 00:41 UTC, kwfk commented on pages/users/settings.tsx
> +  const [setting, setSetting] = useState(initial);
initial doesn't need to be a prop
you can initialize state by putting in the `useState` like `useState('edit')`

2020-11-09 00:41 UTC, kwfk commented on pages/users/settings.tsx
> +  const hiddenPassword: string = '*'.repeat(SampleUser.Password.length);
let's use a constant length like 6

2020-11-09 00:41 UTC, kwfk commented on pages/users/settings.tsx
> +  const [setting, setSetting] = useState(initial);
it might be good to actually use integers instead of string

2020-11-09 00:41 UTC, kwfk commented on pages/users/settings.tsx
> +  const hiddenPassword: string = '*'.repeat(SampleUser.Password.length);
so just `hiddenPassword = '******'`

2020-11-09 00:41 UTC, kwfk commented on styles/users/SettingsEdit.module.css
> +.content {
if the multiple components have the same styles you can import the same stylesheet to multiple components
feel free to ask me for clarification

2020-11-09 00:41 UTC, kwfk commented on pages/users/settings.tsx
> +      </div>
we can probably move the conditional inside the parent components

2020-11-09 00:41 UTC, kwfk commented on components/user/save.tsx
> +        defaultValue={password}
don't show actual password

2020-11-11 09:46 UTC, kwfk requested changes
I think the component naming is a little confusing. let's use `SettingsEdit` for when the user can edit the settings then `SettingsShow` as the viewing state

Also, move the component stylesheets to a shared stylesheet in `components/user/User.module.css` since it's exactly the same. Any comments added to the component stylesheet should also go in the same shared stylesheet

2020-11-11 09:46 UTC, kwfk commented on pages/users/settings.tsx
> +    ) : undefined;
let's use `null` instead of undefined

2020-11-11 09:46 UTC, kwfk commented on pages/users/settings.tsx
> +    setting === 0 ? undefined : (
null here too

2020-11-11 09:46 UTC, kwfk commented on pages/users/settings.tsx
> +  const editButton: typeof Button =
you don't have to type the variable bc Typescript will implicitly know what it is

2020-11-11 09:46 UTC, kwfk commented on pages/users/settings.tsx
> +  const userComponent: React.ReactElement =
no type needed here too

2020-11-11 09:46 UTC, kwfk commented on pages/users/settings.tsx
> +  const saveButton: typeof Button =
no type needed

2020-11-11 09:46 UTC, kwfk commented on components/user/Save/index.tsx
> +  userType,
remove unused prop

2020-11-11 09:46 UTC, kwfk commented on components/user/Edit/index.tsx
> +  userType,
remove unused prop

2020-11-11 09:46 UTC, kwfk commented on styles/users/SettingsEdit.module.css
> +.content {
rename file to `Settings.module.css`

2020-11-11 09:46 UTC, kwfk commented on components/user/Edit/Edit.module.css
> +  margin-top: 10px;
add
```css
height: 40px;
align-items: center;
```

2020-11-11 09:46 UTC, kwfk commented on components/user/Edit/Edit.module.css
> +  margin-top: 10px;
this should be in the shared stylesheet

2020-11-11 09:46 UTC, kwfk commented on components/user/Edit/Edit.module.css
> +.text {
remove this style

2020-11-11 09:46 UTC, kwfk commented on styles/users/SettingsEdit.module.css
> +  margin-top: 10%;
change width to 60% and remove margin-top

2020-11-11 09:46 UTC, kwfk commented on styles/users/SettingsEdit.module.css
> +  flex-direction: column;
remove flex-direction

2020-11-11 09:46 UTC, kwfk commented on styles/users/SettingsEdit.module.css
> +  height: 100%;
change height to `calc(100vh - 85px);`

2020-11-15 00:51 UTC, bry-gavino commented
Hey Fred!! I found that it was actually easier to not use components for the "change email" part. I also ended up making a new page for the "change password" part. As always,  let me know if you want me to change anything!
<img width="1680" alt="Screen Shot 2020-11-14 at 4 21 27 PM" src="https://user-images.githubusercontent.com/60284767/99160204-72095c80-2699-11eb-869d-f27a0f4c70bf.png">
<img width="1675" alt="Screen Shot 2020-11-14 at 4 21 47 PM" src="https://user-images.githubusercontent.com/60284767/99160206-75044d00-2699-11eb-9455-9e03f53959d5.png">
<img width="1676" alt="Screen Shot 2020-11-14 at 4 21 55 PM" src="https://user-images.githubusercontent.com/60284767/99160208-76ce1080-2699-11eb-8530-3fc2ab6aaafc.png">

2020-11-16 09:47 UTC, kwfk reviewed
let's change the stepper to be highlighted at one step at a time
i.e. https://material-ui.com/components/steppers/#non-linear-alternative-label

2020-11-16 09:47 UTC, kwfk commented on components/user/EmailVerify/index.tsx
> +  const [open, setOpen] = React.useState(true);
import useState instead
```typescript
import { useState } from 'react'
```

2020-11-16 09:47 UTC, kwfk commented on pages/users/password_change.tsx
> +import Layout from 'components/Layout';
you want page components to use `-` instead of `_`

2020-11-16 09:47 UTC, kwfk commented on pages/users/password_change.tsx
> +import Layout from 'components/Layout';
let's also rename the component to `ChangePassword`

2020-11-16 09:47 UTC, kwfk commented on pages/users/settings.tsx
> +}
we can use CSS `text-transform: capitalize` to capitalize text

2020-11-16 09:47 UTC, kwfk commented on components/user/ProgressStepper/index.tsx
> +  const handleNext: void = () => {
void should go after the parentheses

2020-11-16 10:42 UTC, kwfk requested changes
nice work! there some more minor changes needed here and tere

center the ChangePassword component with the same CSS style as the ProfileSettings page

2020-11-16 10:42 UTC, kwfk commented on pages/users/settings.tsx
> +      <EmailVerify />
let's not have the email verify show for now (we may create a custom component for toasts later)

2020-11-16 10:42 UTC, kwfk commented on styles/users/Settings.module.css
> +  height: calc(100vh - 85px);
change to `min-height`

2020-11-16 10:42 UTC, kwfk commented on pages/users/settings.tsx
> +            <Button variant="outlined" color="primary" disableElevation>
add onClick to go to ChangePassword page
see this to see how to use NextJS router to go to pages
https://github.com/calblueprint/nbjc/blob/a51a7af389736ee893665f6727ace20bf1a205b3/components/Layout.tsx#L46

2020-11-16 10:42 UTC, kwfk commented on pages/users/password_change.tsx
> +            </Link>
see this to see how to use router to go to another page
https://github.com/calblueprint/nbjc/blob/a51a7af389736ee893665f6727ace20bf1a205b3/components/Layout.tsx#L46

2020-11-16 10:42 UTC, kwfk commented on pages/users/password_change.tsx
> +                label={sampleUserData[0].email}
label is an email?

2020-11-16 10:42 UTC, kwfk commented on pages/users/password_change.tsx
> +import { sampleUserData } from '../../utils/sample-data';
sample user data should not be used

2020-11-16 10:42 UTC, kwfk commented on components/user/ProgressStepper/index.tsx
> +  const [activeStep, setActiveStep] = React.useState(0);
import useState separately

2020-11-16 10:42 UTC, kwfk commented on styles/users/Settings.module.css
> +  height: calc(100vh - 105px);
change to `min-height`

2020-11-16 10:42 UTC, kwfk commented on styles/users/PasswordChange.module.css
> +  height: calc(100vh - 105px);
change to `min-height`

2020-11-16 10:42 UTC, kwfk commented on pages/users/settings.tsx
> +          </Link>
use router to link
https://github.com/calblueprint/nbjc/blob/a51a7af389736ee893665f6727ace20bf1a205b3/components/Layout.tsx#L46

2020-11-16 10:47 UTC, kwfk commented
I pushed some minor CSS refactoring so you'll want to pull before continuing

2020-11-18 19:53 UTC, kwfk requested changes
Looking good! Mentioned that the stepper is currently overflowing. Other than that, it should be nearing approval!

2020-11-18 19:53 UTC, kwfk commented on styles/users/PasswordChange.module.css
> +  min-height: calc(100vh - 85px);
this should be `100vh - 105px`

2020-11-18 19:53 UTC, kwfk commented on styles/users/Settings.module.css
> +  min-height: calc(100vh - 85px);
this should be `100vh - 105px`

2020-11-18 19:53 UTC, kwfk commented on pages/users/change-password.tsx
> +              <Button color="primary" variant="contained" onClick={() => router.push('../users/settings')} disableElevation>
change to `/users/settings` no dots

2020-11-18 19:53 UTC, kwfk commented on pages/users/change-password.tsx
> +import Layout from 'components/Layout';
you'll need to run prettier here
you can do so with the shortcut `cmd+option+f`

2020-11-18 19:53 UTC, kwfk commented on pages/users/settings.tsx
> +            onClick={() => router.push('../users/change-password')}
change to `/users/change-password` no dots

2020-11-18 22:51 UTC, kwfk approved these changes
one small styling change then should be good!

2020-11-18 22:51 UTC, kwfk commented on components/user/ProgressStepper/ProgressStepper.module.css
> +  height: 15px;
make height 12px to match designs

2020-11-18 22:51 UTC, kwfk commented on components/user/ProgressStepper/ProgressStepper.module.css
> +.progress {
add `border-radius: 36px`

2020-11-18 23:06 UTC, merged