Sonja/update mod dash 2
calblueprint/nbjc pull request #26
Opened 2020-11-12 03:33 UTC by Sonjajo

Updated the moderator dashboard to have scrolling and added a few buttons. Redid the layout for the orgDetail that pops up to match figma. 
Still to be done:
- fix styles of left AppBar with the treasury version that Elizabeth and I talked about: https://mui-treasury.com/styles/tabs/#Apple
- add drawer for Notepad button
- add popup window for rejection history
- look into custom drawer left scrollbar, material UI doesn't have functionality we need

_Required for visual changes_

![image](https://user-images.githubusercontent.com/30053749/98892080-61b47000-2454-11eb-872d-00e66f157547.png)

CC: @kwfk

2020-11-13 05:54 UTC, elixawu commented
minor change, but the accept and decline buttons on the bottom should be swapped order (accept on right)

2020-11-15 22:39 UTC, kwfk requested changes
nice work! it looks really nice. there are some minor changes i commented

you may want to add spacing between the demographic chips

2020-11-15 22:39 UTC, kwfk commented on pages/mod2.tsx
> +import MailIcon from '@material-ui/icons/Mail';
collapse to one line import
i.e.
```typescript
import { Drawer, List } from '@material-ui/core'
```

2020-11-15 22:39 UTC, kwfk commented on pages/mod2.tsx
> +import CssBaseline from '@material-ui/core/CssBaseline';
this is imported at base root so don't need to be imported here

2020-11-15 22:39 UTC, kwfk commented on styles/Moderator.module.css
> +  width: 70%;
if using a percentage, you want the elements on the same level to equal 100%

2020-11-15 22:39 UTC, kwfk commented on styles/Moderator.module.css
> +  width: 400px;
if using pixels, you want the other element in the same level to span the rest of the width

2020-11-15 22:39 UTC, kwfk commented on pages/registration.tsx
> +import { Form } from 'interfaces/index';
was this change necessary?

2020-11-15 22:39 UTC, kwfk commented on components/moderator/OrgDetail/index.tsx
> +              // eslint-disable-next-line jsx-a11y/no-static-element-interactions, jsx-a11y/click-events-have-key-events
these eslint-disables are actually not needed!

2020-11-15 22:39 UTC, kwfk commented on styles/Moderator.module.css
> +  width: 400px;
i think leaving this as a pixel width would be better

2020-11-15 22:39 UTC, kwfk commented on styles/Moderator.module.css
> +  width: 70%;
then changing this as `calc(100% - 400px)`

2020-11-19 01:09 UTC, Sonjajo commented on pages/registration.tsx
> +import { Form } from 'interfaces/index';
nope you're right, i reverted it

2020-11-19 01:36 UTC, kwfk requested changes
looking good! just some minor clean up

2020-11-19 01:36 UTC, kwfk commented on interfaces/index.ts
> +};
is this being used?

2020-11-19 01:36 UTC, kwfk commented on pages/moderator.tsx
> +// };
let's remove this

2020-11-19 01:36 UTC, kwfk commented on pages/moderator.tsx
> +export const getServerSideProps: GetServerSideProps = async (context) => {
remove unused prop `context`

2020-11-19 01:36 UTC, kwfk commented on pages/moderator.tsx
> +  console.log(items);
remove console log

2020-11-19 01:52 UTC, kwfk approved these changes
Nice work!

2020-11-19 02:03 UTC, merged