Bryanna/toast component
calblueprint/nbjc pull request #43
Opened 2020-12-03 03:03 UTC by bry-gavino

Made a Toast component with 2 different alert styles and 1 error style. _(see screenshots below)_

## Screenshots

<img width="593" alt="Screen Shot 2020-12-02 at 6 50 40 PM" src="https://user-images.githubusercontent.com/60284767/100957965-488d6500-34d0-11eb-8aaf-f04af74a82d4.png">
The comments for 'acceptedAlert', 'verifyEmailAlert', and 'userExistsError' are pretty self-explanatory. Underneath //general , this is where you can customize the Toast component's message and choose what style to use. 

**verticalPos?** and **horizontalPos?** are props you can pass in to place the Toast in different places of the screen.

The other props with ?s are passed in when you want to customize the Toast.

Customized Toast:
<img width="1680" alt="Screen Shot 2020-12-02 at 6 53 17 PM" src="https://user-images.githubusercontent.com/60284767/100958288-eb45e380-34d0-11eb-9c8a-d2e79a20824c.png">

The different Figma Toast designs:
<img width="1680" alt="Screen Shot 2020-12-02 at 6 53 34 PM" src="https://user-images.githubusercontent.com/60284767/100958324-fb5dc300-34d0-11eb-8405-4b08bf27a4b8.png">
<img width="1680" alt="Screen Shot 2020-12-02 at 6 53 46 PM" src="https://user-images.githubusercontent.com/60284767/100958330-fdc01d00-34d0-11eb-81c1-aee6e3072106.png">
<img width="1677" alt="Screen Shot 2020-12-02 at 6 54 01 PM" src="https://user-images.githubusercontent.com/60284767/100958336-fe58b380-34d0-11eb-92a0-2891bf9426f9.png">

CC: @kwfk

2021-04-11 23:39 UTC, claalmve commented
This PR is brilliant! Apologies it took so long to approve, but just made some minor type changes and code abbreviation. I played around with the different states and really liked how easy it was to use from both the user's and dev's standpoints. Great work!

2021-04-11 23:39 UTC, claalmve approved these changes

2021-04-11 23:42 UTC, claalmve reviewed
My only comment was whether or not we still needed the `react-toastify` package, as it seems like the code is fully functional without it.

2021-04-11 23:42 UTC, claalmve commented on package.json
> +    "react-toastify": "^6.1.0"
Is this package still needed?

2021-04-12 00:31 UTC, kwfk commented
ah i had some changes that i'll push very soon

2021-04-12 00:32 UTC, kwfk requested changes
there are some changes i made before i will push soon

2021-04-12 01:16 UTC, kwfk commented
![image](https://user-images.githubusercontent.com/9738398/114328608-fd283a80-9af1-11eb-9921-bdb1e291f702.png)

2021-04-12 01:34 UTC, kwfk approved these changes
pushed changes

2021-04-12 03:53 UTC, merged